name: Kicker Job to keep the Repository active

on:
  # workflow_dispatch is mandatory, so that Artifactory can trigger
  # the workflow through GitHub REST API.
  schedule:
    - cron: '0 6 1 * *'
  workflow_dispatch:
  
jobs:
  kick-repo-to-be-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Append new month
      run: |
        date +"Update %Y, Month %m" >> kickerlist.txt
      
    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

        git add -A
        git commit -m "Push new month"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
